In [11]:
import pandas as pd
import json
with open('/content/DataEngineeringQ2.json') as file:
    data = json.load(file)

df = pd.json_normalize(data)
df12 = pd.DataFrame(df)

print(df)

         _id appointmentId     phoneNumber      patientDetails._id  \
0   T6hf3rb5     40d2-9c9f     96686896670               T6hb630b3
1   T65g3rb5      40dbtc9f      9496368916               T6h33b300
2   T7g6Srb5      g3Wt5c9f      7787204833                TjhB4373
3   94bg8W8d      fb6-a535      9376756879                 6df4R5b
4   T6h8H56c       67h7KL9      5267384241                lK9hy06a
5    T9Jh8c8        Hy7Y91   +919826374025                 kI9d5c6
6   9Is624b9     10dY8a-4a      7587265252                i9R324b7
7   T8H9c3c6      e8056Ye8      5586958767  T6h41b5ad3d8002ad9c3c4
8    T8Ud380     dbc0-c66b      9987602525                T9Iy347e
9    T345fG4        1576a7      9234354366                 T4Rb1a2
10  T4F6a175       b6Te4ac      4863281056                Tr4T2173
11   TW3r002        bu5Qfb      8687986800                  T6Wa50
12   6U6Ra36       86U8Y45                                 65sRa36
13   u7Y7Aa5       Ufd7231      7152684236                 UG67231
14   T3R5dec       E4u5Ea2                                 E4u5Ea2
15   T4E7Ge6      T4E3e410      9184723620                 T4E7Ge6
16  E5336545       04Re22d                                 04Re22d
17   T7Ys58b      af9784hf      5847346075                u7dWa589
18  Y874Us5w       I8eW201      9064537237                 TU7e913
19   Y7s5G42     f7r501cb1                                 H8s2d40
20  Y7eE5cd8    cf092c8t6c       992727892                   u9cd6
21   I9984e8      O02n262e      6888324121                 Pdh97S6
22  Tu78a783      5dfN9s41      8248594521               h02U8a781
23   U9D2w6c      cc86re0f   +917938475936  T6h40a5ad3d8002ad9c06a
24  T6hY6sEe       bd99dU7  +9124648979746                  Y7sHec
25    H7sT6c        bcWe50   +916883788633   T6h408981ayf32b63bcfa
26   8Utyd5b       7au8se3   +916636278363                T6U67af9
27  y87Ta5c7      432cT213      6525356535                 R53Et5W
28  Ub7S65b7      D3fFr42c                                dE3r$2b5
29   yD7s2d7       7uyT6Rs   +919093872282                 TI93Hd5
30   I9Sb4e8        O02n2e   +916888324121                 Pdh97S6

    patientDetails.firstName patientDetails.lastName patientDetails.emailId  \
0                        Css
1                     Lokesh
2                      Shila                     Das
3                    Bhavika             Ben Panchal
4                 Raghu Viju
5               Dinesh Kumar
6                      Lalit                Sankhwal
7                       Ravi
8                     Dinesh
9                     Sanjay
10                    Akshay                  Akshay
11                   Nirmala
12                    Satish
13                Kalaiarasi              Kalaiarasi
14              Satyanaaryan
15                   Nivitha
16                    Tejpal
17                  Nandhini
18                  Dhanamma
19                    Kushal
20                    Daniya                   Zehra
21                       Jay                  Sharma
22                   Preethi
23  VITTHAL SHANKARRAO GHATE                                            NaN
24                    Naresh
25                    Suresh                 Gaikwad
26                 Govardhan
27                Rajeshwari
28                   Santosh
29                 Tarachand
30                       Jay                  Sharma

   patientDetails.gender patientDetails.alternateContact  \
0
1                      M                             NaN
2                    NaN                             NaN
3                      F                             NaN
4                    NaN
5                      M                             NaN
6                      M
7                    NaN                             NaN
8                      M                             NaN
9                      M                             NaN
10                     M                             NaN
11                     F                             NaN
12                   NaN                             NaN
13                     F
14                   NaN
15                     F                             NaN
16                     M                             NaN
17                     F                             NaN
18                     F                             NaN
19                   NaN                             NaN
20                     F                             NaN
21                     M                             NaN
22                     F                             NaN
23                   NaN                   +917797689682
24                     M                             NaN
25                   NaN
26                   NaN
27                     F                             NaN
28                     F                             NaN
29                     M
30                     M                             NaN

    patientDetails.birthDate  ... consultationData.procedures  \
0                       None  ...                          []
1   1996-05-16T18:30:00.000Z  ...                          []
2                        NaN  ...                          []
3   1988-04-24T14:30:00.000Z  ...                          []
4                        NaN  ...                          []
5   1983-05-16T18:30:00.000Z  ...                          []
6   2003-06-27T14:30:00.000Z  ...                          []
7                        NaN  ...                          []
8   1983-05-16T18:30:00.000Z  ...                          []
9   1998-05-16T18:30:00.000Z  ...                          []
10  1988-04-08T00:00:00.000Z  ...                          []
11  1971-05-16T18:30:00.000Z  ...                          []
12  1970-05-16T18:30:00.000Z  ...                          []
13  1997-07-31T00:00:00.000Z  ...                          []
14                       NaN  ...                          []
15  1997-05-16T18:30:00.000Z  ...                          []
16  1972-05-16T18:30:00.000Z  ...                          []
17  2001-05-16T18:30:00.000Z  ...                          []
18                       NaN  ...                          []
19                       NaN  ...                          []
20  2001-08-27T00:00:00.000Z  ...                          []
21  1998-11-19T23:30:00.000Z  ...                          []
22  1996-05-16T18:30:00.000Z  ...                          []
23                       NaN  ...                          []
24  1992-05-16T18:30:00.000Z  ...                          []
25                       NaN  ...                          []
26                       NaN  ...                          []
27  1999-05-16T18:30:00.000Z  ...                          []
28  1972-05-16T18:30:00.000Z  ...                          []
29  1980-03-22T18:30:00.000Z  ...                          []
30  1991-11-19T23:30:00.000Z  ...                          []

   consultationData.prognosis consultationData.sharePrescription  \
0                          []                              False
1                          []                              False
2                          []                              False
3                          []                              False
4                          []                              False
5                          []                              False
6                          []                              False
7                          []                              False
8                          []                              False
9                          []                              False
10                         []                              False
11                         []                              False
12                         []                              False
13                         []                              False
14                         []                              False
15                         []                              False
16                         []                              False
17                         []                              False
18                         []                              False
19                         []                              False
20                         []                              False
21                         []                              False
22                         []                              False
23                         []                              False
24                         []                              False
25                         []                              False
26                         []                              False
27                         []                              False
28                         []                              False
29                         []                              False
30                         []                              False

   patientDetails.phrId patientDetails.chat._id patientDetails.customId  \
0                   NaN                     NaN                     NaN
1                   NaN                     NaN                     NaN
2          63b5hvy614d5                     NaN                     NaN
3              644nig7y                     NaN                     NaN
4                   NaN                     NaN                     NaN
5                   NaN                09hUb5c7            3FPEUCW8HACJ
6              67Yt2b97                     NaN                     NaN
7                   NaN  T6h41b5ad3d8002ad9c3c5            8AV4ICI5I389
8                   NaN                T9IsT37f            0308MSAHYR8K
9                   NaN                7Yd9b1a3            8S7A3D4K4WZH
10              6E48U79                 Tr4W174            83AH0K04SSTV
11                  NaN  T6h3635ad3d8002ad9b001            832ZIS6ZCAHH
12                  NaN                  6Y6a36            YW883CARSES3
13              T6a7231                     NaN                     NaN
14                  NaN                 E4u5Ea2                 E4u5Ea2
15                  NaN                     NaN                     NaN
16                  NaN                 04Re22d                 04Re22d
17                  NaN                     NaN                     NaN
18                  NaN               u8e6fgd14                 y7ewr5w
19                  NaN                     NaN                     NaN
20           6463U8s231                     NaN                     NaN
21              Jus0480                     NaN                     NaN
22                  NaN                T6h9a782               H8NdI3MAW
23                  NaN  T6h40a1becc5002908b235            83AAWWI24W63
24                  NaN                     NaN                     NaN
25                  NaN                 Hsb690S                ABCD1419
26                  NaN               u7sg9be5a                 Gya7sfw
27                  NaN            T6h2fT5535c6                K44RwH0T
28                  NaN                     NaN                     NaN
29                  NaN                 TH8W2d6                 90hjdX2
30              Jus0480                     NaN                     NaN

   patientDetails.chat.channelId consultationData._id  \
0                            NaN                  NaN
1                            NaN                  NaN
2                            NaN                  NaN
3                            NaN                  NaN
4                            NaN                  NaN
5                            NaN                  NaN
6                            NaN                  NaN
7                            NaN                  NaN
8                            NaN                  NaN
9                            NaN                  NaN
10                      9IrR9ce7                  NaN
11                           NaN                  NaN
12                           NaN                  NaN
13                           NaN             6T67a6a4
14                           NaN                  NaN
15                           NaN                  NaN
16                           NaN                  NaN
17                           NaN                  NaN
18                           NaN                  NaN
19                           NaN                  NaN
20                           NaN                  NaN
21                           NaN                  NaN
22                           NaN                  NaN
23                           NaN                  NaN
24                           NaN                  NaN
25                           NaN                  NaN
26                           NaN                  NaN
27                           NaN                  NaN
28                           NaN                  NaN
29                           NaN                  NaN
30                           NaN                  NaN

   consultationData.updatedAt consultationData.createdAt
0                         NaN                        NaN
1                         NaN                        NaN
2                         NaN                        NaN
3                         NaN                        NaN
4                         NaN                        NaN
5                         NaN                        NaN
6                         NaN                        NaN
7                         NaN                        NaN
8                         NaN                        NaN
9                         NaN                        NaN
10                        NaN                        NaN
11                        NaN                        NaN
12                        NaN                        NaN
13   2023-05-16T14:42:50.620Z   2023-05-16T14:42:50.620Z
14                        NaN                        NaN
15                        NaN                        NaN
16                        NaN                        NaN
17                        NaN                        NaN
18                        NaN                        NaN
19                        NaN                        NaN
20                        NaN                        NaN
21                        NaN                        NaN
22                        NaN                        NaN
23                        NaN                        NaN
24                        NaN                        NaN
25                        NaN                        NaN
26                        NaN                        NaN
27                        NaN                        NaN
28                        NaN                        NaN
29                        NaN                        NaN
30                        NaN                        NaN

[31 rows x 43 columns]

In [12]:
df12

,_id,appointmentId,phoneNumber,patientDetails._id,patientDetails.firstName,patientDetails.lastName,patientDetails.emailId,patientDetails.gender,patientDetails.alternateContact,patientDetails.birthDate,...,consultationData.procedures,consultationData.prognosis,consultationData.sharePrescription,patientDetails.phrId,patientDetails.chat._id,patientDetails.customId,patientDetails.chat.channelId,consultationData._id,consultationData.updatedAt,consultationData.createdAt
0,T6hf3rb5,40d2-9c9f,96686896670,T6hb630b3,Css,,,,,None,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,T65g3rb5,40dbtc9f,9496368916,T6h33b300,Lokesh,,,M,NaN,1996-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,T7g6Srb5,g3Wt5c9f,7787204833,TjhB4373,Shila,Das,,NaN,NaN,NaN,...,[],[],False,63b5hvy614d5,NaN,NaN,NaN,NaN,NaN,NaN
3,94bg8W8d,fb6-a535,9376756879,6df4R5b,Bhavika,Ben Panchal,,F,NaN,1988-04-24T14:30:00.000Z,...,[],[],False,644nig7y,NaN,NaN,NaN,NaN,NaN,NaN
4,T6h8H56c,67h7KL9,5267384241,lK9hy06a,Raghu Viju,,,NaN,,NaN,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,T9Jh8c8,Hy7Y91,+919826374025,kI9d5c6,Dinesh Kumar,,,M,NaN,1983-05-16T18:30:00.000Z,...,[],[],False,NaN,09hUb5c7,3FPEUCW8HACJ,NaN,NaN,NaN,NaN
6,9Is624b9,10dY8a-4a,7587265252,i9R324b7,Lalit,Sankhwal,,M,,2003-06-27T14:30:00.000Z,...,[],[],False,67Yt2b97,NaN,NaN,NaN,NaN,NaN,NaN
7,T8H9c3c6,e8056Ye8,5586958767,T6h41b5ad3d8002ad9c3c4,Ravi,,,NaN,NaN,NaN,...,[],[],False,NaN,T6h41b5ad3d8002ad9c3c5,8AV4ICI5I389,NaN,NaN,NaN,NaN
8,T8Ud380,dbc0-c66b,9987602525,T9Iy347e,Dinesh,,,M,NaN,1983-05-16T18:30:00.000Z,...,[],[],False,NaN,T9IsT37f,0308MSAHYR8K,NaN,NaN,NaN,NaN
9,T345fG4,1576a7,9234354366,T4Rb1a2,Sanjay,,,M,NaN,1998-05-16T18:30:00.000Z,...,[],[],False,NaN,7Yd9b1a3,8S7A3D4K4WZH,NaN,NaN,NaN,NaN
10,T4F6a175,b6Te4ac,4863281056,Tr4T2173,Akshay,Akshay,,M,NaN,1988-04-08T00:00:00.000Z,...,[],[],False,6E48U79,Tr4W174,83AH0K04SSTV,9IrR9ce7,NaN,NaN,NaN
11,TW3r002,bu5Qfb,8687986800,T6Wa50,Nirmala,,,F,NaN,1971-05-16T18:30:00.000Z,...,[],[],False,NaN,T6h3635ad3d8002ad9b001,832ZIS6ZCAHH,NaN,NaN,NaN,NaN
12,6U6Ra36,86U8Y45,,65sRa36,Satish,,,NaN,NaN,1970-05-16T18:30:00.000Z,...,[],[],False,NaN,6Y6a36,YW883CARSES3,NaN,NaN,NaN,NaN
13,u7Y7Aa5,Ufd7231,7152684236,UG67231,Kalaiarasi,Kalaiarasi,,F,,1997-07-31T00:00:00.000Z,...,[],[],False,T6a7231,NaN,NaN,NaN,6T67a6a4,2023-05-16T14:42:50.620Z,2023-05-16T14:42:50.620Z
14,T3R5dec,E4u5Ea2,,E4u5Ea2,Satyanaaryan,,,NaN,,NaN,...,[],[],False,NaN,E4u5Ea2,E4u5Ea2,NaN,NaN,NaN,NaN
15,T4E7Ge6,T4E3e410,9184723620,T4E7Ge6,Nivitha,,,F,NaN,1997-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,E5336545,04Re22d,,04Re22d,Tejpal,,,M,NaN,1972-05-16T18:30:00.000Z,...,[],[],False,NaN,04Re22d,04Re22d,NaN,NaN,NaN,NaN
17,T7Ys58b,af9784hf,5847346075,u7dWa589,Nandhini,,,F,NaN,2001-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Y874Us5w,I8eW201,9064537237,TU7e913,Dhanamma,,,F,NaN,NaN,...,[],[],False,NaN,u8e6fgd14,y7ewr5w,NaN,NaN,NaN,NaN
19,Y7s5G42,f7r501cb1,,H8s2d40,Kushal,,,NaN,NaN,NaN,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Y7eE5cd8,cf092c8t6c,992727892,u9cd6,Daniya,Zehra,,F,NaN,2001-08-27T00:00:00.000Z,...,[],[],False,6463U8s231,NaN,NaN,NaN,NaN,NaN,NaN
21,I9984e8,O02n262e,6888324121,Pdh97S6,Jay,Sharma,,M,NaN,1998-11-19T23:30:00.000Z,...,[],[],False,Jus0480,NaN,NaN,NaN,NaN,NaN,NaN
22,Tu78a783,5dfN9s41,8248594521,h02U8a781,Preethi,,,F,NaN,1996-05-16T18:30:00.000Z,...,[],[],False,NaN,T6h9a782,H8NdI3MAW,NaN,NaN,NaN,NaN
23,U9D2w6c,cc86re0f,+917938475936,T6h40a5ad3d8002ad9c06a,VITTHAL SHANKARRAO GHATE,,NaN,NaN,+917797689682,NaN,...,[],[],False,NaN,T6h40a1becc5002908b235,83AAWWI24W63,NaN,NaN,NaN,NaN
24,T6hY6sEe,bd99dU7,+9124648979746,Y7sHec,Naresh,,,M,NaN,1992-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,H7sT6c,bcWe50,+916883788633,T6h408981ayf32b63bcfa,Suresh,Gaikwad,,NaN,,NaN,...,[],[],False,NaN,Hsb690S,ABCD1419,NaN,NaN,NaN,NaN
26,8Utyd5b,7au8se3,+916636278363,T6U67af9,Govardhan,,,NaN,,NaN,...,[],[],False,NaN,u7sg9be5a,Gya7sfw,NaN,NaN,NaN,NaN
27,y87Ta5c7,432cT213,6525356535,R53Et5W,Rajeshwari,,,F,NaN,1999-05-16T18:30:00.000Z,...,[],[],False,NaN,T6h2fT5535c6,K44RwH0T,NaN,NaN,NaN,NaN
28,Ub7S65b7,D3fFr42c,,dE3r$2b5,Santosh,,,F,NaN,1972-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,yD7s2d7,7uyT6Rs,+919093872282,TI93Hd5,Tarachand,,,M,,1980-03-22T18:30:00.000Z,...,[],[],False,NaN,TH8W2d6,90hjdX2,NaN,NaN,NaN,NaN
30,I9Sb4e8,O02n2e,+916888324121,Pdh97S6,Jay,Sharma,,M,NaN,1991-11-19T23:30:00.000Z,...,[],[],False,Jus0480,NaN,NaN,NaN,NaN,NaN,NaN

Warning: Total number of columns (43) exceeds max_columns (20) limiting to first (20) columns.

In [18]:
print(df12["consultationData.medicines"])

0     [{'medicineId': '619404', 'medicineName': 'A',...
1     [{'medicineId': '619404', 'medicineName': 'A',...
2     [{'medicineId': '619404', 'medicineName': 'B',...
3     [{'medicineId': '619704', 'medicineName': 'B',...
4     [{'medicineId': '619384', 'medicineName': 'D',...
5     [{'medicineId': '643404', 'medicineName': 'A',...
6     [{'medicineId': '632304', 'medicineName': 'D',...
7     [{'medicineId': '619404', 'medicineName': 'A',...
8     [{'medicineId': '619504', 'medicineName': 'E',...
9                                                    []
10    [{'medicineId': '619504', 'medicineName': 'E',...
11    [{'medicineId': '619504', 'medicineName': 'E',...
12                                                   []
13    [{'medicineId': '619504', 'medicineName': 'A',...
14                                                   []
15    [{'medicineId': '619504', 'medicineName': 'B',...
16    [{'medicineId': '619504', 'medicineName': 'C',...
17    [{'medicineId': '619504', 'medicineName': 'A',...
18    [{'medicineId': '619504', 'medicineName': 'A',...
19                                                   []
20    [{'medicineId': '619504', 'medicineName': 'D',...
21    [{'medicineId': '612504', 'medicineName': 'D',...
22    [{'medicineId': '611504', 'medicineName': 'A',...
23    [{'medicineId': '612504', 'medicineName': 'A',...
24                                                   []
25    [{'medicineId': '612504', 'medicineName': 'D',...
26    [{'medicineId': '612504', 'medicineName': 'C',...
27    [{'medicineId': '612504', 'medicineName': 'A',...
28                                                   []
29    [{'medicineId': '612504', 'medicineName': 'A',...
30    [{'medicineId': '612504', 'medicineName': 'A',...
Name: consultationData.medicines, dtype: object

In [5]:
df.isnull().sum()

_id                                                0
appointmentId                                      0
phoneNumber                                        0
patientDetails._id                                 0
patientDetails.firstName                           0
patientDetails.lastName                            0
patientDetails.emailId                             1
patientDetails.gender                              9
patientDetails.alternateContact                   22
patientDetails.birthDate                          10
consultationData.adviceTemplates                   0
consultationData.advices                           0
consultationData.attachments                       0
consultationData.chiefComplaints                   0
consultationData.customOne                         0
consultationData.customThree                       0
consultationData.customTwo                         0
consultationData.disease                           0
consultationData.doctorNotes                       0
consultationData.emergencyInstructions             0
consultationData.emergencyInstructionsTemplate     0
consultationData.emrTemplates                      0
consultationData.examinationNote                   0
consultationData.findings                          0
consultationData.investigationInstructions         0
consultationData.investigationTemplates            0
consultationData.investigations                    0
consultationData.isBalicAppointment                0
consultationData.isQuickPrescription               0
consultationData.labTest                           0
consultationData.languageCode                      0
consultationData.medicineTemplates                 0
consultationData.medicines                         0
consultationData.procedures                        0
consultationData.prognosis                         0
consultationData.sharePrescription                 0
patientDetails.phrId                              23
patientDetails.chat._id                           15
patientDetails.customId                           15
patientDetails.chat.channelId                     30
consultationData._id                              30
consultationData.updatedAt                        30
consultationData.createdAt                        30
dtype: int64

In [10]:
patient_details = [entry["patientDetails"] for entry in data]
missing_firstName = 0
missing_lastName = 0
missing_DOB = 0

for patient in patient_details:
    if not patient.get("firstName"):
        missing_firstName += 1
    if not patient.get("lastName"):
        missing_lastName += 1
    if not patient.get("birthDate"):
        missing_DOB += 1

total_entries = len(patient_details)
missing_firstName_percentage = (missing_firstName / total_entries) * 100
missing_lastName_percentage = (missing_lastName / total_entries) * 100
missing_DOB_percentage = (missing_DOB / total_entries) * 100
missing_firstName_percentage_rounded = round(missing_firstName_percentage, 2)
missing_lastName_percentage_rounded = round(missing_lastName_percentage, 2)
missing_DOB_percentage_rounded = round(missing_DOB_percentage, 2)

missing_firstName_percentage_rounded, missing_lastName_percentage_rounded, missing_DOB_percentage_rounded

(0.0, 70.97, 32.26)

In [7]:
import json
from collections import Counter


with open("/content/DataEngineeringQ2.json") as file:
    data = json.load(file)


genders = [entry["patientDetails"].get("gender", "") for entry in data]
mode_gender = Counter(genders).most_common(1)[0][0]
imputed_genders = [gender if gender else mode_gender for gender in genders]
total_count = len(imputed_genders)
female_count = imputed_genders.count("F")
female_percentage = (female_count / total_count) * 100
female_percentage_rounded = round(female_percentage, 2)
female_percentage_rounded

32.26

In [16]:
def calculate_age(birth_date):
    today = datetime.today()
    birth_date = datetime.strptime(birth_date.split("T")[0], "%Y-%m-%d")
    return today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
adult_count = 0

for patient in patient_details:
    birth_date = patient.get("birthDate")
    if birth_date:
        age = calculate_age(birth_date)
        patient["ageGroup"] = age_group(age)
        if patient["ageGroup"] == "Adult":
            adult_count += 1

adult_count

AttributeError: module 'datetime' has no attribute 'today'

In [21]:
def is_valid_number(phone_number):
    if phone_number.startswith('+'):
        phone_number = phone_number[1:]
    if phone_number.startswith('91'):
        phone_number = phone_number[2:]
    if phone_number.isdigit() and len(phone_number) == 10:
        return 6000000000 <= int(phone_number) <= 9999999999
    return False



df = pd.json_normalize(data)
df['isValidMobile'] = df['phoneNumber'].apply(is_valid_number)
valid_phone_numbers_count = df['isValidMobile'].sum()
valid_phone_numbers_count

18